#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  anon_sym_GT = 2,
  sym_doctype = 3,
  anon_sym_LT = 4,
  anon_sym_SLASH_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_EQ = 7,
  sym_attribute_name = 8,
  sym_attribute_value = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_DQUOTE = 11,
  sym_text = 12,
  sym_pat_03aa317 = 13,
  sym_pat_58fbb2e = 14,
  sym_pat_98d585a = 15,
  sym_start_tag_name = 16,
  sym_script_start_tag_name = 17,
  sym_style_start_tag_name = 18,
  sym_end_tag_name = 19,
  sym_erroneous_end_tag_name = 20,
  sym_implicit_end_tag = 21,
  sym_raw_text = 22,
  sym_comment = 23,
  sym_fragment = 24,
  sym_doctype_ = 25,
  sym_node = 26,
  sym_element = 27,
  sym_script_element = 28,
  sym_style_element = 29,
  sym_start_tag = 30,
  sym_script_start_tag = 31,
  sym_style_start_tag = 32,
  sym_self_closing_tag = 33,
  sym_end_tag = 34,
  sym_erroneous_end_tag = 35,
  sym_attribute = 36,
  sym_quoted_attribute_value = 37,
  aux_sym_fragment_repeat1 = 38,
  aux_sym_start_tag_repeat1 = 39,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [anon_sym_GT] = ">",
  [sym_doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_text] = "text",
  [sym_pat_03aa317] = "pat_03aa317",
  [sym_pat_58fbb2e] = "pat_58fbb2e",
  [sym_pat_98d585a] = "pat_98d585a",
  [sym_start_tag_name] = "start_tag_name",
  [sym_script_start_tag_name] = "script_start_tag_name",
  [sym_style_start_tag_name] = "style_start_tag_name",
  [sym_end_tag_name] = "end_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym_implicit_end_tag] = "implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype_] = "doctype_",
  [sym_node] = "node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "script_start_tag",
  [sym_style_start_tag] = "style_start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [anon_sym_GT] = anon_sym_GT,
  [sym_doctype] = sym_doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_text] = sym_text,
  [sym_pat_03aa317] = sym_pat_03aa317,
  [sym_pat_58fbb2e] = sym_pat_58fbb2e,
  [sym_pat_98d585a] = sym_pat_98d585a,
  [sym_start_tag_name] = sym_start_tag_name,
  [sym_script_start_tag_name] = sym_script_start_tag_name,
  [sym_style_start_tag_name] = sym_style_start_tag_name,
  [sym_end_tag_name] = sym_end_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym_implicit_end_tag] = sym_implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype_] = sym_doctype_,
  [sym_node] = sym_node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_script_start_tag,
  [sym_style_start_tag] = sym_style_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_03aa317] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_58fbb2e] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_98d585a] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype_] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(29);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_doctype);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_pat_03aa317);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_pat_03aa317);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_pat_58fbb2e);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_pat_58fbb2e);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_pat_98d585a);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_pat_98d585a);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13, .external_lex_state = 2},
  [2] = {.lex_state = 13, .external_lex_state = 3},
  [3] = {.lex_state = 13, .external_lex_state = 3},
  [4] = {.lex_state = 13, .external_lex_state = 3},
  [5] = {.lex_state = 13, .external_lex_state = 3},
  [6] = {.lex_state = 13, .external_lex_state = 2},
  [7] = {.lex_state = 13, .external_lex_state = 3},
  [8] = {.lex_state = 13, .external_lex_state = 2},
  [9] = {.lex_state = 13, .external_lex_state = 3},
  [10] = {.lex_state = 4, .external_lex_state = 4},
  [11] = {.lex_state = 13, .external_lex_state = 3},
  [12] = {.lex_state = 13, .external_lex_state = 2},
  [13] = {.lex_state = 13, .external_lex_state = 3},
  [14] = {.lex_state = 4, .external_lex_state = 4},
  [15] = {.lex_state = 13, .external_lex_state = 3},
  [16] = {.lex_state = 13, .external_lex_state = 3},
  [17] = {.lex_state = 13, .external_lex_state = 3},
  [18] = {.lex_state = 13, .external_lex_state = 2},
  [19] = {.lex_state = 13, .external_lex_state = 3},
  [20] = {.lex_state = 13, .external_lex_state = 3},
  [21] = {.lex_state = 13, .external_lex_state = 3},
  [22] = {.lex_state = 13, .external_lex_state = 2},
  [23] = {.lex_state = 13, .external_lex_state = 3},
  [24] = {.lex_state = 13, .external_lex_state = 2},
  [25] = {.lex_state = 4, .external_lex_state = 4},
  [26] = {.lex_state = 13, .external_lex_state = 3},
  [27] = {.lex_state = 13, .external_lex_state = 3},
  [28] = {.lex_state = 13, .external_lex_state = 2},
  [29] = {.lex_state = 13, .external_lex_state = 2},
  [30] = {.lex_state = 4, .external_lex_state = 4},
  [31] = {.lex_state = 13, .external_lex_state = 3},
  [32] = {.lex_state = 4, .external_lex_state = 4},
  [33] = {.lex_state = 13, .external_lex_state = 2},
  [34] = {.lex_state = 13, .external_lex_state = 2},
  [35] = {.lex_state = 13, .external_lex_state = 2},
  [36] = {.lex_state = 13, .external_lex_state = 3},
  [37] = {.lex_state = 13, .external_lex_state = 2},
  [38] = {.lex_state = 13, .external_lex_state = 2},
  [39] = {.lex_state = 13, .external_lex_state = 2},
  [40] = {.lex_state = 13, .external_lex_state = 2},
  [41] = {.lex_state = 13, .external_lex_state = 3},
  [42] = {.lex_state = 1, .external_lex_state = 2},
  [43] = {.lex_state = 4, .external_lex_state = 2},
  [44] = {.lex_state = 4, .external_lex_state = 2},
  [45] = {.lex_state = 4, .external_lex_state = 4},
  [46] = {.lex_state = 1, .external_lex_state = 2},
  [47] = {.lex_state = 4, .external_lex_state = 2},
  [48] = {.lex_state = 4, .external_lex_state = 2},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 4, .external_lex_state = 4},
  [51] = {.lex_state = 4, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 5},
  [53] = {.lex_state = 0, .external_lex_state = 5},
  [54] = {.lex_state = 4, .external_lex_state = 4},
  [55] = {.lex_state = 0, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 6},
  [57] = {.lex_state = 0, .external_lex_state = 6},
  [58] = {.lex_state = 0, .external_lex_state = 6},
  [59] = {.lex_state = 4, .external_lex_state = 4},
  [60] = {.lex_state = 4, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 6},
  [62] = {.lex_state = 0, .external_lex_state = 6},
  [63] = {.lex_state = 0, .external_lex_state = 6},
  [64] = {.lex_state = 0, .external_lex_state = 7},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 2, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 7},
  [69] = {.lex_state = 3, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 4, .external_lex_state = 2},
  [72] = {.lex_state = 4, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 6},
  [75] = {.lex_state = 2, .external_lex_state = 2},
  [76] = {.lex_state = 3, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 12, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 8},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 9},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 12, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 9},
  [95] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_start_tag_name = 0,
  ts_external_token_script_start_tag_name = 1,
  ts_external_token_style_start_tag_name = 2,
  ts_external_token_end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token_implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_start_tag_name] = sym_start_tag_name,
  [ts_external_token_script_start_tag_name] = sym_script_start_tag_name,
  [ts_external_token_style_start_tag_name] = sym_style_start_tag_name,
  [ts_external_token_end_tag_name] = sym_end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_implicit_end_tag] = sym_implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_start_tag_name] = ACTIONS(1),
    [sym_script_start_tag_name] = ACTIONS(1),
    [sym_style_start_tag_name] = ACTIONS(1),
    [sym_end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym_implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(79),
    [sym_doctype_] = STATE(33),
    [sym_node] = STATE(6),
    [sym_element] = STATE(33),
    [sym_script_element] = STATE(33),
    [sym_style_element] = STATE(33),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(55),
    [sym_style_start_tag] = STATE(58),
    [sym_self_closing_tag] = STATE(12),
    [sym_erroneous_end_tag] = STATE(33),
    [aux_sym_fragment_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(23), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_end_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(16), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [45] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(37), 1,
      sym_end_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(16), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [90] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(18), 1,
      sym_end_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(3), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(16), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [135] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(31), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(13), 1,
      sym_end_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(2), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(16), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [180] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_self_closing_tag,
    STATE(55), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(8), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [222] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      anon_sym_LT_SLASH,
    ACTIONS(44), 1,
      sym_text,
    ACTIONS(47), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(16), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [264] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_LT_BANG,
    ACTIONS(52), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(58), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_self_closing_tag,
    STATE(55), 1,
      sym_script_start_tag,
    STATE(58), 1,
      sym_style_start_tag,
    STATE(8), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [306] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(61), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [319] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_GT,
    ACTIONS(67), 1,
      anon_sym_SLASH_GT,
    ACTIONS(69), 1,
      sym_attribute_name,
    STATE(32), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(71), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(77), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(79), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [375] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_GT,
    ACTIONS(85), 1,
      anon_sym_SLASH_GT,
    STATE(10), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [392] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(77), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(87), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(91), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [431] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(79), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [444] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(95), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(99), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(103), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(109), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [496] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(109), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [509] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(113), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [522] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_GT,
    ACTIONS(69), 1,
      sym_attribute_name,
    ACTIONS(115), 1,
      anon_sym_SLASH_GT,
    STATE(32), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [539] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(117), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(121), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [565] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(127), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [578] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(71), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [591] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_GT,
    ACTIONS(129), 1,
      anon_sym_SLASH_GT,
    STATE(25), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [608] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(127), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_attribute_name,
    ACTIONS(131), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(32), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(87), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [649] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(91), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [662] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(117), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(113), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [688] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(61), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [701] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(103), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(99), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [727] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(95), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [740] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(136), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [753] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_attribute_value,
    ACTIONS(142), 1,
      anon_sym_SQUOTE,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      sym_quoted_attribute_value,
  [769] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_GT,
    ACTIONS(148), 1,
      sym_attribute_name,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [783] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_attribute_name,
    ACTIONS(150), 1,
      anon_sym_GT,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [797] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_EQ,
    ACTIONS(152), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [809] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_attribute_value,
    ACTIONS(158), 1,
      anon_sym_SQUOTE,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      sym_quoted_attribute_value,
  [825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_attribute_name,
    ACTIONS(162), 1,
      anon_sym_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [839] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_attribute_name,
    ACTIONS(164), 1,
      anon_sym_GT,
    STATE(44), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [853] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_GT,
    ACTIONS(166), 1,
      sym_attribute_name,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [876] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(152), 2,
      anon_sym_GT,
      sym_attribute_name,
  [887] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_start_tag_name,
    ACTIONS(175), 1,
      sym_script_start_tag_name,
    ACTIONS(177), 1,
      sym_style_start_tag_name,
  [900] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_script_start_tag_name,
    ACTIONS(177), 1,
      sym_style_start_tag_name,
    ACTIONS(179), 1,
      sym_start_tag_name,
  [913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [922] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT_SLASH,
    ACTIONS(185), 1,
      sym_raw_text,
    STATE(22), 1,
      sym_end_tag,
  [935] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LT_SLASH,
    ACTIONS(189), 1,
      sym_raw_text,
    STATE(36), 1,
      sym_end_tag,
  [948] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LT_SLASH,
    ACTIONS(191), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
  [961] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT_SLASH,
    ACTIONS(193), 1,
      sym_raw_text,
    STATE(24), 1,
      sym_end_tag,
  [974] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      anon_sym_GT,
      sym_attribute_name,
  [991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [999] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1015] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_end_tag_name,
    ACTIONS(205), 1,
      sym_erroneous_end_tag_name,
  [1025] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    ACTIONS(209), 1,
      sym_pat_98d585a,
  [1045] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT_SLASH,
    STATE(38), 1,
      sym_end_tag,
  [1055] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(211), 1,
      sym_end_tag_name,
  [1065] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_SQUOTE,
    ACTIONS(213), 1,
      sym_pat_58fbb2e,
  [1075] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LT_SLASH,
    STATE(20), 1,
      sym_end_tag,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1101] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LT_SLASH,
    STATE(21), 1,
      sym_end_tag,
  [1111] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1119] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      sym_pat_98d585a,
  [1129] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_SQUOTE,
    ACTIONS(221), 1,
      sym_pat_58fbb2e,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_doctype,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_GT,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_SQUOTE,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_pat_03aa317,
  [1174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_GT,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_erroneous_end_tag_name,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_GT,
  [1195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_GT,
  [1202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_GT,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_end_tag_name,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_erroneous_end_tag_name,
  [1244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_pat_03aa317,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_GT,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_end_tag_name,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_doctype,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 306,
  [SMALL_STATE(10)] = 319,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 349,
  [SMALL_STATE(13)] = 362,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 392,
  [SMALL_STATE(16)] = 405,
  [SMALL_STATE(17)] = 418,
  [SMALL_STATE(18)] = 431,
  [SMALL_STATE(19)] = 444,
  [SMALL_STATE(20)] = 457,
  [SMALL_STATE(21)] = 470,
  [SMALL_STATE(22)] = 483,
  [SMALL_STATE(23)] = 496,
  [SMALL_STATE(24)] = 509,
  [SMALL_STATE(25)] = 522,
  [SMALL_STATE(26)] = 539,
  [SMALL_STATE(27)] = 552,
  [SMALL_STATE(28)] = 565,
  [SMALL_STATE(29)] = 578,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 608,
  [SMALL_STATE(32)] = 621,
  [SMALL_STATE(33)] = 636,
  [SMALL_STATE(34)] = 649,
  [SMALL_STATE(35)] = 662,
  [SMALL_STATE(36)] = 675,
  [SMALL_STATE(37)] = 688,
  [SMALL_STATE(38)] = 701,
  [SMALL_STATE(39)] = 714,
  [SMALL_STATE(40)] = 727,
  [SMALL_STATE(41)] = 740,
  [SMALL_STATE(42)] = 753,
  [SMALL_STATE(43)] = 769,
  [SMALL_STATE(44)] = 783,
  [SMALL_STATE(45)] = 797,
  [SMALL_STATE(46)] = 809,
  [SMALL_STATE(47)] = 825,
  [SMALL_STATE(48)] = 839,
  [SMALL_STATE(49)] = 853,
  [SMALL_STATE(50)] = 867,
  [SMALL_STATE(51)] = 876,
  [SMALL_STATE(52)] = 887,
  [SMALL_STATE(53)] = 900,
  [SMALL_STATE(54)] = 913,
  [SMALL_STATE(55)] = 922,
  [SMALL_STATE(56)] = 935,
  [SMALL_STATE(57)] = 948,
  [SMALL_STATE(58)] = 961,
  [SMALL_STATE(59)] = 974,
  [SMALL_STATE(60)] = 983,
  [SMALL_STATE(61)] = 991,
  [SMALL_STATE(62)] = 999,
  [SMALL_STATE(63)] = 1007,
  [SMALL_STATE(64)] = 1015,
  [SMALL_STATE(65)] = 1025,
  [SMALL_STATE(66)] = 1035,
  [SMALL_STATE(67)] = 1045,
  [SMALL_STATE(68)] = 1055,
  [SMALL_STATE(69)] = 1065,
  [SMALL_STATE(70)] = 1075,
  [SMALL_STATE(71)] = 1085,
  [SMALL_STATE(72)] = 1093,
  [SMALL_STATE(73)] = 1101,
  [SMALL_STATE(74)] = 1111,
  [SMALL_STATE(75)] = 1119,
  [SMALL_STATE(76)] = 1129,
  [SMALL_STATE(77)] = 1139,
  [SMALL_STATE(78)] = 1146,
  [SMALL_STATE(79)] = 1153,
  [SMALL_STATE(80)] = 1160,
  [SMALL_STATE(81)] = 1167,
  [SMALL_STATE(82)] = 1174,
  [SMALL_STATE(83)] = 1181,
  [SMALL_STATE(84)] = 1188,
  [SMALL_STATE(85)] = 1195,
  [SMALL_STATE(86)] = 1202,
  [SMALL_STATE(87)] = 1209,
  [SMALL_STATE(88)] = 1216,
  [SMALL_STATE(89)] = 1223,
  [SMALL_STATE(90)] = 1230,
  [SMALL_STATE(91)] = 1237,
  [SMALL_STATE(92)] = 1244,
  [SMALL_STATE(93)] = 1251,
  [SMALL_STATE(94)] = 1258,
  [SMALL_STATE(95)] = 1265,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(95),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(52),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(91),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(16),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(77),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(53),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(83),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(33),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype_, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype_, 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(45),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(51),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [227] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = (const uint16_t *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
