#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 3
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype__token1 = 2,
  anon_sym_GT = 3,
  sym_doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_attribute_value_token1 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_attribute_value_token2 = 14,
  sym_text = 15,
  anon_sym_LT_QMARKxml = 16,
  anon_sym_QMARK_GT = 17,
  sym_semgrep_metavariable = 18,
  sym_start_tag_name = 19,
  sym_script_start_tag_name = 20,
  sym_style_start_tag_name = 21,
  sym_end_tag_name = 22,
  sym_erroneous_end_tag_name = 23,
  sym_implicit_end_tag = 24,
  sym_raw_text = 25,
  sym_comment = 26,
  sym_fragment = 27,
  sym_doctype_ = 28,
  sym_node = 29,
  sym_element = 30,
  sym_script_element = 31,
  sym_style_element = 32,
  sym_start_tag = 33,
  sym_script_start_tag = 34,
  sym_style_start_tag = 35,
  sym_self_closing_tag = 36,
  sym_end_tag = 37,
  sym_erroneous_end_tag = 38,
  sym_attribute = 39,
  sym_quoted_attribute_value = 40,
  sym_toplevel_node = 41,
  sym_toplevel_attribute = 42,
  sym_xmldoctype = 43,
  sym_semgrep_start_tag = 44,
  sym_semgrep_end_tag = 45,
  aux_sym_fragment_repeat1 = 46,
  aux_sym_element_repeat1 = 47,
  aux_sym_start_tag_repeat1 = 48,
  alias_sym_pat_03aa317 = 49,
  alias_sym_pat_58fbb2e = 50,
  alias_sym_pat_98d585a = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype__token1] = "doctype__token1",
  [anon_sym_GT] = ">",
  [sym_doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "quoted_attribute_value_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "quoted_attribute_value_token2",
  [sym_text] = "text",
  [anon_sym_LT_QMARKxml] = "<\?xml",
  [anon_sym_QMARK_GT] = "\?>",
  [sym_semgrep_metavariable] = "semgrep_metavariable",
  [sym_start_tag_name] = "start_tag_name",
  [sym_script_start_tag_name] = "script_start_tag_name",
  [sym_style_start_tag_name] = "style_start_tag_name",
  [sym_end_tag_name] = "end_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym_implicit_end_tag] = "implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype_] = "doctype_",
  [sym_node] = "node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "script_start_tag",
  [sym_style_start_tag] = "style_start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_toplevel_node] = "toplevel_node",
  [sym_toplevel_attribute] = "toplevel_attribute",
  [sym_xmldoctype] = "xmldoctype",
  [sym_semgrep_start_tag] = "semgrep_start_tag",
  [sym_semgrep_end_tag] = "semgrep_end_tag",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [alias_sym_pat_03aa317] = "pat_03aa317",
  [alias_sym_pat_58fbb2e] = "pat_58fbb2e",
  [alias_sym_pat_98d585a] = "pat_98d585a",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype__token1] = aux_sym_doctype__token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym_doctype] = sym_doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [sym_text] = sym_text,
  [anon_sym_LT_QMARKxml] = anon_sym_LT_QMARKxml,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [sym_semgrep_metavariable] = sym_semgrep_metavariable,
  [sym_start_tag_name] = sym_start_tag_name,
  [sym_script_start_tag_name] = sym_script_start_tag_name,
  [sym_style_start_tag_name] = sym_style_start_tag_name,
  [sym_end_tag_name] = sym_end_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym_implicit_end_tag] = sym_implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype_] = sym_doctype_,
  [sym_node] = sym_node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_script_start_tag,
  [sym_style_start_tag] = sym_style_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_toplevel_node] = sym_toplevel_node,
  [sym_toplevel_attribute] = sym_toplevel_attribute,
  [sym_xmldoctype] = sym_xmldoctype,
  [sym_semgrep_start_tag] = sym_semgrep_start_tag,
  [sym_semgrep_end_tag] = sym_semgrep_end_tag,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [alias_sym_pat_03aa317] = alias_sym_pat_03aa317,
  [alias_sym_pat_58fbb2e] = alias_sym_pat_58fbb2e,
  [alias_sym_pat_98d585a] = alias_sym_pat_98d585a,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype__token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_QMARKxml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_semgrep_metavariable] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype_] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_toplevel_node] = {
    .visible = true,
    .named = true,
  },
  [sym_toplevel_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_xmldoctype] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_pat_03aa317] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_pat_58fbb2e] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_pat_98d585a] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_pat_03aa317,
  },
  [2] = {
    [1] = alias_sym_pat_58fbb2e,
  },
  [3] = {
    [1] = alias_sym_pat_98d585a,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '?') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'x') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 19:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_doctype__token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_doctype__token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_doctype);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '?') ADVANCE(10);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '>') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '=') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_QMARKxml);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_semgrep_metavariable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 20, .external_lex_state = 2},
  [2] = {.lex_state = 20, .external_lex_state = 2},
  [3] = {.lex_state = 20, .external_lex_state = 2},
  [4] = {.lex_state = 4, .external_lex_state = 3},
  [5] = {.lex_state = 4, .external_lex_state = 3},
  [6] = {.lex_state = 4, .external_lex_state = 3},
  [7] = {.lex_state = 4, .external_lex_state = 3},
  [8] = {.lex_state = 4, .external_lex_state = 3},
  [9] = {.lex_state = 20, .external_lex_state = 2},
  [10] = {.lex_state = 20, .external_lex_state = 2},
  [11] = {.lex_state = 20, .external_lex_state = 2},
  [12] = {.lex_state = 20, .external_lex_state = 2},
  [13] = {.lex_state = 20, .external_lex_state = 2},
  [14] = {.lex_state = 20, .external_lex_state = 2},
  [15] = {.lex_state = 20, .external_lex_state = 2},
  [16] = {.lex_state = 20, .external_lex_state = 2},
  [17] = {.lex_state = 20, .external_lex_state = 2},
  [18] = {.lex_state = 20, .external_lex_state = 2},
  [19] = {.lex_state = 20, .external_lex_state = 2},
  [20] = {.lex_state = 20, .external_lex_state = 2},
  [21] = {.lex_state = 20, .external_lex_state = 2},
  [22] = {.lex_state = 20, .external_lex_state = 2},
  [23] = {.lex_state = 20, .external_lex_state = 2},
  [24] = {.lex_state = 20, .external_lex_state = 2},
  [25] = {.lex_state = 20, .external_lex_state = 2},
  [26] = {.lex_state = 20, .external_lex_state = 2},
  [27] = {.lex_state = 20, .external_lex_state = 2},
  [28] = {.lex_state = 20, .external_lex_state = 2},
  [29] = {.lex_state = 20, .external_lex_state = 2},
  [30] = {.lex_state = 4, .external_lex_state = 3},
  [31] = {.lex_state = 4, .external_lex_state = 3},
  [32] = {.lex_state = 4, .external_lex_state = 3},
  [33] = {.lex_state = 4, .external_lex_state = 3},
  [34] = {.lex_state = 4, .external_lex_state = 3},
  [35] = {.lex_state = 4, .external_lex_state = 3},
  [36] = {.lex_state = 4, .external_lex_state = 3},
  [37] = {.lex_state = 20, .external_lex_state = 4},
  [38] = {.lex_state = 4, .external_lex_state = 3},
  [39] = {.lex_state = 20, .external_lex_state = 4},
  [40] = {.lex_state = 4, .external_lex_state = 3},
  [41] = {.lex_state = 4, .external_lex_state = 3},
  [42] = {.lex_state = 4, .external_lex_state = 3},
  [43] = {.lex_state = 4, .external_lex_state = 3},
  [44] = {.lex_state = 4, .external_lex_state = 3},
  [45] = {.lex_state = 4, .external_lex_state = 3},
  [46] = {.lex_state = 20, .external_lex_state = 4},
  [47] = {.lex_state = 20, .external_lex_state = 4},
  [48] = {.lex_state = 4, .external_lex_state = 3},
  [49] = {.lex_state = 4, .external_lex_state = 3},
  [50] = {.lex_state = 4, .external_lex_state = 3},
  [51] = {.lex_state = 4, .external_lex_state = 3},
  [52] = {.lex_state = 4, .external_lex_state = 3},
  [53] = {.lex_state = 20, .external_lex_state = 4},
  [54] = {.lex_state = 4, .external_lex_state = 3},
  [55] = {.lex_state = 1, .external_lex_state = 2},
  [56] = {.lex_state = 20, .external_lex_state = 2},
  [57] = {.lex_state = 5, .external_lex_state = 2},
  [58] = {.lex_state = 5, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 20, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 1, .external_lex_state = 2},
  [63] = {.lex_state = 1, .external_lex_state = 2},
  [64] = {.lex_state = 5, .external_lex_state = 2},
  [65] = {.lex_state = 20, .external_lex_state = 2},
  [66] = {.lex_state = 1, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 20, .external_lex_state = 2},
  [69] = {.lex_state = 20, .external_lex_state = 4},
  [70] = {.lex_state = 20, .external_lex_state = 2},
  [71] = {.lex_state = 20, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 5},
  [73] = {.lex_state = 0, .external_lex_state = 6},
  [74] = {.lex_state = 20, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 5},
  [76] = {.lex_state = 20, .external_lex_state = 2},
  [77] = {.lex_state = 20, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 7},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 5, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 20, .external_lex_state = 4},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 20, .external_lex_state = 4},
  [87] = {.lex_state = 20, .external_lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 5},
  [89] = {.lex_state = 0, .external_lex_state = 5},
  [90] = {.lex_state = 0, .external_lex_state = 8},
  [91] = {.lex_state = 2, .external_lex_state = 2},
  [92] = {.lex_state = 3, .external_lex_state = 2},
  [93] = {.lex_state = 5, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 5},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 5, .external_lex_state = 2},
  [97] = {.lex_state = 5, .external_lex_state = 2},
  [98] = {.lex_state = 2, .external_lex_state = 2},
  [99] = {.lex_state = 20, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 8},
  [101] = {.lex_state = 5, .external_lex_state = 2},
  [102] = {.lex_state = 3, .external_lex_state = 2},
  [103] = {.lex_state = 2, .external_lex_state = 2},
  [104] = {.lex_state = 3, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 18, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 2},
  [117] = {.lex_state = 0, .external_lex_state = 2},
  [118] = {.lex_state = 0, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 2},
  [121] = {.lex_state = 0, .external_lex_state = 9},
  [122] = {.lex_state = 0, .external_lex_state = 9},
  [123] = {.lex_state = 18, .external_lex_state = 2},
  [124] = {.lex_state = 0, .external_lex_state = 2},
  [125] = {.lex_state = 0, .external_lex_state = 2},
  [126] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_start_tag_name = 0,
  ts_external_token_script_start_tag_name = 1,
  ts_external_token_style_start_tag_name = 2,
  ts_external_token_end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token_implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_start_tag_name] = sym_start_tag_name,
  [ts_external_token_script_start_tag_name] = sym_script_start_tag_name,
  [ts_external_token_style_start_tag_name] = sym_style_start_tag_name,
  [ts_external_token_end_tag_name] = sym_end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_implicit_end_tag] = sym_implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LT_QMARKxml] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [sym_semgrep_metavariable] = ACTIONS(1),
    [sym_start_tag_name] = ACTIONS(1),
    [sym_script_start_tag_name] = ACTIONS(1),
    [sym_style_start_tag_name] = ACTIONS(1),
    [sym_end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym_implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(111),
    [sym_doctype_] = STATE(27),
    [sym_element] = STATE(27),
    [sym_script_element] = STATE(27),
    [sym_style_element] = STATE(27),
    [sym_start_tag] = STATE(7),
    [sym_script_start_tag] = STATE(61),
    [sym_style_start_tag] = STATE(59),
    [sym_self_closing_tag] = STATE(15),
    [sym_erroneous_end_tag] = STATE(27),
    [sym_toplevel_node] = STATE(3),
    [sym_toplevel_attribute] = STATE(27),
    [sym_xmldoctype] = STATE(27),
    [sym_semgrep_start_tag] = STATE(52),
    [aux_sym_fragment_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_attribute_name] = ACTIONS(13),
    [anon_sym_LT_QMARKxml] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(22), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(28), 1,
      sym_attribute_name,
    ACTIONS(31), 1,
      anon_sym_LT_QMARKxml,
    STATE(7), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(61), 1,
      sym_script_start_tag,
    STATE(2), 2,
      sym_toplevel_node,
      aux_sym_fragment_repeat1,
    STATE(27), 7,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_toplevel_attribute,
      sym_xmldoctype,
  [50] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      sym_attribute_name,
    ACTIONS(15), 1,
      anon_sym_LT_QMARKxml,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(59), 1,
      sym_style_start_tag,
    STATE(61), 1,
      sym_script_start_tag,
    STATE(2), 2,
      sym_toplevel_node,
      aux_sym_fragment_repeat1,
    STATE(27), 7,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_toplevel_attribute,
      sym_xmldoctype,
  [100] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(40), 1,
      anon_sym_LT_SLASH,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(44), 1,
      sym_implicit_end_tag,
    STATE(6), 1,
      sym_start_tag,
    STATE(41), 1,
      sym_semgrep_end_tag,
    STATE(45), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(8), 2,
      sym_node,
      aux_sym_element_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [151] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(46), 1,
      anon_sym_LT_SLASH,
    ACTIONS(48), 1,
      sym_implicit_end_tag,
    STATE(6), 1,
      sym_start_tag,
    STATE(17), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
    STATE(45), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(8), 2,
      sym_node,
      aux_sym_element_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [202] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(40), 1,
      anon_sym_LT_SLASH,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(50), 1,
      sym_implicit_end_tag,
    STATE(6), 1,
      sym_start_tag,
    STATE(41), 1,
      sym_semgrep_end_tag,
    STATE(43), 1,
      sym_end_tag,
    STATE(45), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(4), 2,
      sym_node,
      aux_sym_element_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [253] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(46), 1,
      anon_sym_LT_SLASH,
    ACTIONS(52), 1,
      sym_implicit_end_tag,
    STATE(6), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
    STATE(45), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(5), 2,
      sym_node,
      aux_sym_element_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [304] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_LT_BANG,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(60), 1,
      anon_sym_LT_SLASH,
    ACTIONS(63), 1,
      sym_text,
    ACTIONS(66), 1,
      sym_implicit_end_tag,
    STATE(6), 1,
      sym_start_tag,
    STATE(45), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_semgrep_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(75), 1,
      sym_script_start_tag,
    STATE(8), 2,
      sym_node,
      aux_sym_element_repeat1,
    STATE(33), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [379] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LT,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [422] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LT,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LT,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [450] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LT,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [464] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [478] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [492] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LT,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LT,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_LT,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [548] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LT,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [576] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_LT,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [604] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LT,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [632] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_attribute_name,
      anon_sym_LT_QMARKxml,
  [646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(152), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LT,
    ACTIONS(96), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LT,
    ACTIONS(112), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LT,
    ACTIONS(156), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_LT,
    ACTIONS(116), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [711] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LT,
    ACTIONS(128), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [724] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_attribute_name,
    ACTIONS(160), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [765] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(167), 1,
      anon_sym_SLASH_GT,
    ACTIONS(169), 1,
      sym_attribute_name,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [795] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [808] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(80), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_LT,
    ACTIONS(132), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(171), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [847] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LT,
    ACTIONS(92), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [860] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      sym_attribute_name,
    ACTIONS(175), 1,
      anon_sym_SLASH_GT,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [877] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_attribute_name,
    ACTIONS(177), 1,
      anon_sym_GT,
    ACTIONS(179), 1,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(84), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [907] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LT,
    ACTIONS(88), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [920] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_LT,
    ACTIONS(181), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [933] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LT,
    ACTIONS(185), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LT,
    ACTIONS(189), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [959] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_attribute_name,
    ACTIONS(177), 1,
      anon_sym_GT,
    ACTIONS(193), 1,
      anon_sym_SLASH_GT,
    STATE(39), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(100), 4,
      sym_implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_text,
  [989] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_attribute_value,
    ACTIONS(197), 1,
      anon_sym_SQUOTE,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_quoted_attribute_value,
  [1005] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      sym_attribute_name,
    STATE(71), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1019] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(207), 1,
      anon_sym_QMARK_GT,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_QMARK_GT,
    ACTIONS(209), 1,
      sym_attribute_name,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1047] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    ACTIONS(214), 1,
      sym_raw_text,
    STATE(24), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
  [1063] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_attribute_name,
    ACTIONS(216), 1,
      anon_sym_GT,
    STATE(68), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1077] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    ACTIONS(218), 1,
      sym_raw_text,
    STATE(26), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
  [1093] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_attribute_value,
    ACTIONS(222), 1,
      anon_sym_SQUOTE,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(101), 1,
      sym_quoted_attribute_value,
  [1109] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_attribute_value,
    ACTIONS(228), 1,
      anon_sym_SQUOTE,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_quoted_attribute_value,
  [1125] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(232), 1,
      anon_sym_QMARK_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1139] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_attribute_name,
    ACTIONS(234), 1,
      anon_sym_GT,
    STATE(70), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1153] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_SQUOTE,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    ACTIONS(236), 1,
      sym_attribute_value,
    STATE(99), 1,
      sym_quoted_attribute_value,
  [1169] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_semgrep_metavariable,
    ACTIONS(240), 1,
      sym_start_tag_name,
    ACTIONS(242), 1,
      sym_script_start_tag_name,
    ACTIONS(244), 1,
      sym_style_start_tag_name,
  [1185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_attribute_name,
    ACTIONS(246), 1,
      anon_sym_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(248), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_attribute_name,
    ACTIONS(252), 1,
      anon_sym_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1225] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_attribute_name,
    ACTIONS(254), 1,
      anon_sym_GT,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1239] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LT_SLASH,
    ACTIONS(258), 1,
      sym_raw_text,
    STATE(35), 1,
      sym_end_tag,
    STATE(41), 1,
      sym_semgrep_end_tag,
  [1255] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_semgrep_metavariable,
    ACTIONS(242), 1,
      sym_script_start_tag_name,
    ACTIONS(244), 1,
      sym_style_start_tag_name,
    ACTIONS(260), 1,
      sym_start_tag_name,
  [1271] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_GT,
    ACTIONS(262), 1,
      sym_attribute_name,
    STATE(74), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1285] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LT_SLASH,
    ACTIONS(265), 1,
      sym_raw_text,
    STATE(38), 1,
      sym_end_tag,
    STATE(41), 1,
      sym_semgrep_end_tag,
  [1301] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_EQ,
    ACTIONS(248), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1321] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_semgrep_metavariable,
    ACTIONS(273), 1,
      sym_end_tag_name,
    ACTIONS(275), 1,
      sym_erroneous_end_tag_name,
  [1334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LT_SLASH,
    STATE(41), 1,
      sym_semgrep_end_tag,
    STATE(49), 1,
      sym_end_tag,
  [1347] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LT_SLASH,
    STATE(31), 1,
      sym_end_tag,
    STATE(41), 1,
      sym_semgrep_end_tag,
  [1360] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_QMARK_GT,
    ACTIONS(277), 1,
      anon_sym_EQ,
    ACTIONS(279), 1,
      sym_attribute_name,
  [1373] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(281), 1,
      sym_semgrep_metavariable,
    ACTIONS(283), 1,
      sym_end_tag_name,
  [1386] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    STATE(14), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1408] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LT_SLASH,
    STATE(16), 1,
      sym_end_tag,
    STATE(28), 1,
      sym_semgrep_end_tag,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_semgrep_metavariable,
    ACTIONS(273), 1,
      sym_end_tag_name,
  [1465] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    ACTIONS(291), 1,
      aux_sym_quoted_attribute_value_token2,
  [1475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
    ACTIONS(293), 1,
      aux_sym_quoted_attribute_value_token1,
  [1485] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_QMARK_GT,
    ACTIONS(78), 1,
      sym_attribute_name,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_QMARK_GT,
    ACTIONS(74), 1,
      sym_attribute_name,
  [1521] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_QMARK_GT,
    ACTIONS(70), 1,
      sym_attribute_name,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_DQUOTE,
    ACTIONS(301), 1,
      aux_sym_quoted_attribute_value_token2,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_semgrep_metavariable,
    ACTIONS(283), 1,
      sym_end_tag_name,
  [1559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_QMARK_GT,
    ACTIONS(303), 1,
      sym_attribute_name,
  [1569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_SQUOTE,
    ACTIONS(305), 1,
      aux_sym_quoted_attribute_value_token1,
  [1579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_DQUOTE,
    ACTIONS(309), 1,
      aux_sym_quoted_attribute_value_token2,
  [1589] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_SQUOTE,
    ACTIONS(311), 1,
      aux_sym_quoted_attribute_value_token1,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_GT,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_GT,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_GT,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      aux_sym_doctype__token1,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_GT,
  [1634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_GT,
  [1641] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      ts_builtin_sym_end,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_GT,
  [1655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_GT,
  [1662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_SQUOTE,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_DQUOTE,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_SQUOTE,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_doctype,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_EQ,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_SQUOTE,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_DQUOTE,
  [1711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_erroneous_end_tag_name,
  [1718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_erroneous_end_tag_name,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      aux_sym_doctype__token1,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_GT,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_DQUOTE,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym_doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 151,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 253,
  [SMALL_STATE(8)] = 304,
  [SMALL_STATE(9)] = 349,
  [SMALL_STATE(10)] = 364,
  [SMALL_STATE(11)] = 379,
  [SMALL_STATE(12)] = 394,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 422,
  [SMALL_STATE(15)] = 436,
  [SMALL_STATE(16)] = 450,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 478,
  [SMALL_STATE(19)] = 492,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 520,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 548,
  [SMALL_STATE(24)] = 562,
  [SMALL_STATE(25)] = 576,
  [SMALL_STATE(26)] = 590,
  [SMALL_STATE(27)] = 604,
  [SMALL_STATE(28)] = 618,
  [SMALL_STATE(29)] = 632,
  [SMALL_STATE(30)] = 646,
  [SMALL_STATE(31)] = 659,
  [SMALL_STATE(32)] = 672,
  [SMALL_STATE(33)] = 685,
  [SMALL_STATE(34)] = 698,
  [SMALL_STATE(35)] = 711,
  [SMALL_STATE(36)] = 724,
  [SMALL_STATE(37)] = 737,
  [SMALL_STATE(38)] = 752,
  [SMALL_STATE(39)] = 765,
  [SMALL_STATE(40)] = 782,
  [SMALL_STATE(41)] = 795,
  [SMALL_STATE(42)] = 808,
  [SMALL_STATE(43)] = 821,
  [SMALL_STATE(44)] = 834,
  [SMALL_STATE(45)] = 847,
  [SMALL_STATE(46)] = 860,
  [SMALL_STATE(47)] = 877,
  [SMALL_STATE(48)] = 894,
  [SMALL_STATE(49)] = 907,
  [SMALL_STATE(50)] = 920,
  [SMALL_STATE(51)] = 933,
  [SMALL_STATE(52)] = 946,
  [SMALL_STATE(53)] = 959,
  [SMALL_STATE(54)] = 976,
  [SMALL_STATE(55)] = 989,
  [SMALL_STATE(56)] = 1005,
  [SMALL_STATE(57)] = 1019,
  [SMALL_STATE(58)] = 1033,
  [SMALL_STATE(59)] = 1047,
  [SMALL_STATE(60)] = 1063,
  [SMALL_STATE(61)] = 1077,
  [SMALL_STATE(62)] = 1093,
  [SMALL_STATE(63)] = 1109,
  [SMALL_STATE(64)] = 1125,
  [SMALL_STATE(65)] = 1139,
  [SMALL_STATE(66)] = 1153,
  [SMALL_STATE(67)] = 1169,
  [SMALL_STATE(68)] = 1185,
  [SMALL_STATE(69)] = 1199,
  [SMALL_STATE(70)] = 1211,
  [SMALL_STATE(71)] = 1225,
  [SMALL_STATE(72)] = 1239,
  [SMALL_STATE(73)] = 1255,
  [SMALL_STATE(74)] = 1271,
  [SMALL_STATE(75)] = 1285,
  [SMALL_STATE(76)] = 1301,
  [SMALL_STATE(77)] = 1312,
  [SMALL_STATE(78)] = 1321,
  [SMALL_STATE(79)] = 1334,
  [SMALL_STATE(80)] = 1347,
  [SMALL_STATE(81)] = 1360,
  [SMALL_STATE(82)] = 1373,
  [SMALL_STATE(83)] = 1386,
  [SMALL_STATE(84)] = 1399,
  [SMALL_STATE(85)] = 1408,
  [SMALL_STATE(86)] = 1421,
  [SMALL_STATE(87)] = 1430,
  [SMALL_STATE(88)] = 1439,
  [SMALL_STATE(89)] = 1447,
  [SMALL_STATE(90)] = 1455,
  [SMALL_STATE(91)] = 1465,
  [SMALL_STATE(92)] = 1475,
  [SMALL_STATE(93)] = 1485,
  [SMALL_STATE(94)] = 1495,
  [SMALL_STATE(95)] = 1503,
  [SMALL_STATE(96)] = 1511,
  [SMALL_STATE(97)] = 1521,
  [SMALL_STATE(98)] = 1531,
  [SMALL_STATE(99)] = 1541,
  [SMALL_STATE(100)] = 1549,
  [SMALL_STATE(101)] = 1559,
  [SMALL_STATE(102)] = 1569,
  [SMALL_STATE(103)] = 1579,
  [SMALL_STATE(104)] = 1589,
  [SMALL_STATE(105)] = 1599,
  [SMALL_STATE(106)] = 1606,
  [SMALL_STATE(107)] = 1613,
  [SMALL_STATE(108)] = 1620,
  [SMALL_STATE(109)] = 1627,
  [SMALL_STATE(110)] = 1634,
  [SMALL_STATE(111)] = 1641,
  [SMALL_STATE(112)] = 1648,
  [SMALL_STATE(113)] = 1655,
  [SMALL_STATE(114)] = 1662,
  [SMALL_STATE(115)] = 1669,
  [SMALL_STATE(116)] = 1676,
  [SMALL_STATE(117)] = 1683,
  [SMALL_STATE(118)] = 1690,
  [SMALL_STATE(119)] = 1697,
  [SMALL_STATE(120)] = 1704,
  [SMALL_STATE(121)] = 1711,
  [SMALL_STATE(122)] = 1718,
  [SMALL_STATE(123)] = 1725,
  [SMALL_STATE(124)] = 1732,
  [SMALL_STATE(125)] = 1739,
  [SMALL_STATE(126)] = 1746,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(117),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(67),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(121),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(118),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(64),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(126),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(73),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(122),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2), SHIFT_REPEAT(33),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, .production_id = 3),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, .production_id = 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, .production_id = 2),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, .production_id = 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype_, 4, .production_id = 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype_, 4, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xmldoctype, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_xmldoctype, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toplevel_attribute, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_toplevel_attribute, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_end_tag, 3),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_end_tag, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xmldoctype, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_xmldoctype, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toplevel_node, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_toplevel_node, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(69),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_start_tag, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_start_tag, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_start_tag, 4),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_start_tag, 4),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(81),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(76),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [325] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
