#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  anon_sym_GT = 2,
  sym_doctype = 3,
  anon_sym_LT = 4,
  anon_sym_SLASH_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_EQ = 7,
  sym_attribute_name = 8,
  sym_attribute_value = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_DQUOTE = 11,
  sym_text = 12,
  sym_semgrep_metavariable = 13,
  sym_pat_03aa317 = 14,
  sym_pat_58fbb2e = 15,
  sym_pat_98d585a = 16,
  sym_start_tag_name = 17,
  sym_script_start_tag_name = 18,
  sym_style_start_tag_name = 19,
  sym_end_tag_name = 20,
  sym_erroneous_end_tag_name = 21,
  sym_implicit_end_tag = 22,
  sym_raw_text = 23,
  sym_comment = 24,
  sym_fragment = 25,
  sym_doctype_ = 26,
  sym_node = 27,
  sym_element = 28,
  sym_script_element = 29,
  sym_style_element = 30,
  sym_start_tag = 31,
  sym_script_start_tag = 32,
  sym_style_start_tag = 33,
  sym_self_closing_tag = 34,
  sym_end_tag = 35,
  sym_erroneous_end_tag = 36,
  sym_attribute = 37,
  sym_quoted_attribute_value = 38,
  sym_semgrep_element = 39,
  sym_semgrep_start_tag = 40,
  sym_semgrep_end_tag = 41,
  aux_sym_fragment_repeat1 = 42,
  aux_sym_start_tag_repeat1 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [anon_sym_GT] = ">",
  [sym_doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_text] = "text",
  [sym_semgrep_metavariable] = "semgrep_metavariable",
  [sym_pat_03aa317] = "pat_03aa317",
  [sym_pat_58fbb2e] = "pat_58fbb2e",
  [sym_pat_98d585a] = "pat_98d585a",
  [sym_start_tag_name] = "start_tag_name",
  [sym_script_start_tag_name] = "script_start_tag_name",
  [sym_style_start_tag_name] = "style_start_tag_name",
  [sym_end_tag_name] = "end_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym_implicit_end_tag] = "implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype_] = "doctype_",
  [sym_node] = "node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "script_start_tag",
  [sym_style_start_tag] = "style_start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_semgrep_element] = "semgrep_element",
  [sym_semgrep_start_tag] = "semgrep_start_tag",
  [sym_semgrep_end_tag] = "semgrep_end_tag",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [anon_sym_GT] = anon_sym_GT,
  [sym_doctype] = sym_doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_text] = sym_text,
  [sym_semgrep_metavariable] = sym_semgrep_metavariable,
  [sym_pat_03aa317] = sym_pat_03aa317,
  [sym_pat_58fbb2e] = sym_pat_58fbb2e,
  [sym_pat_98d585a] = sym_pat_98d585a,
  [sym_start_tag_name] = sym_start_tag_name,
  [sym_script_start_tag_name] = sym_script_start_tag_name,
  [sym_style_start_tag_name] = sym_style_start_tag_name,
  [sym_end_tag_name] = sym_end_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym_implicit_end_tag] = sym_implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype_] = sym_doctype_,
  [sym_node] = sym_node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_script_start_tag,
  [sym_style_start_tag] = sym_style_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_semgrep_element] = sym_semgrep_element,
  [sym_semgrep_start_tag] = sym_semgrep_start_tag,
  [sym_semgrep_end_tag] = sym_semgrep_end_tag,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_metavariable] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_03aa317] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_58fbb2e] = {
    .visible = true,
    .named = true,
  },
  [sym_pat_98d585a] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype_] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_element] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_semgrep_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '$') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_doctype);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_semgrep_metavariable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_pat_03aa317);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_pat_03aa317);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_pat_58fbb2e);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_pat_58fbb2e);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_pat_98d585a);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_pat_98d585a);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 14, .external_lex_state = 2},
  [2] = {.lex_state = 14, .external_lex_state = 3},
  [3] = {.lex_state = 14, .external_lex_state = 3},
  [4] = {.lex_state = 14, .external_lex_state = 3},
  [5] = {.lex_state = 14, .external_lex_state = 3},
  [6] = {.lex_state = 14, .external_lex_state = 2},
  [7] = {.lex_state = 14, .external_lex_state = 2},
  [8] = {.lex_state = 14, .external_lex_state = 2},
  [9] = {.lex_state = 14, .external_lex_state = 3},
  [10] = {.lex_state = 14, .external_lex_state = 2},
  [11] = {.lex_state = 14, .external_lex_state = 2},
  [12] = {.lex_state = 14, .external_lex_state = 2},
  [13] = {.lex_state = 14, .external_lex_state = 3},
  [14] = {.lex_state = 4, .external_lex_state = 4},
  [15] = {.lex_state = 14, .external_lex_state = 2},
  [16] = {.lex_state = 14, .external_lex_state = 3},
  [17] = {.lex_state = 4, .external_lex_state = 4},
  [18] = {.lex_state = 14, .external_lex_state = 3},
  [19] = {.lex_state = 14, .external_lex_state = 3},
  [20] = {.lex_state = 4, .external_lex_state = 4},
  [21] = {.lex_state = 14, .external_lex_state = 3},
  [22] = {.lex_state = 14, .external_lex_state = 2},
  [23] = {.lex_state = 4, .external_lex_state = 4},
  [24] = {.lex_state = 14, .external_lex_state = 3},
  [25] = {.lex_state = 4, .external_lex_state = 4},
  [26] = {.lex_state = 14, .external_lex_state = 2},
  [27] = {.lex_state = 14, .external_lex_state = 2},
  [28] = {.lex_state = 14, .external_lex_state = 2},
  [29] = {.lex_state = 14, .external_lex_state = 3},
  [30] = {.lex_state = 14, .external_lex_state = 2},
  [31] = {.lex_state = 14, .external_lex_state = 3},
  [32] = {.lex_state = 14, .external_lex_state = 3},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 14, .external_lex_state = 3},
  [36] = {.lex_state = 14, .external_lex_state = 3},
  [37] = {.lex_state = 14, .external_lex_state = 2},
  [38] = {.lex_state = 14, .external_lex_state = 3},
  [39] = {.lex_state = 14, .external_lex_state = 3},
  [40] = {.lex_state = 14, .external_lex_state = 3},
  [41] = {.lex_state = 14, .external_lex_state = 3},
  [42] = {.lex_state = 14, .external_lex_state = 2},
  [43] = {.lex_state = 14, .external_lex_state = 3},
  [44] = {.lex_state = 14, .external_lex_state = 2},
  [45] = {.lex_state = 14, .external_lex_state = 2},
  [46] = {.lex_state = 14, .external_lex_state = 2},
  [47] = {.lex_state = 14, .external_lex_state = 3},
  [48] = {.lex_state = 14, .external_lex_state = 2},
  [49] = {.lex_state = 14, .external_lex_state = 2},
  [50] = {.lex_state = 14, .external_lex_state = 2},
  [51] = {.lex_state = 14, .external_lex_state = 3},
  [52] = {.lex_state = 1, .external_lex_state = 2},
  [53] = {.lex_state = 4, .external_lex_state = 4},
  [54] = {.lex_state = 14, .external_lex_state = 2},
  [55] = {.lex_state = 4, .external_lex_state = 2},
  [56] = {.lex_state = 14, .external_lex_state = 2},
  [57] = {.lex_state = 4, .external_lex_state = 2},
  [58] = {.lex_state = 4, .external_lex_state = 4},
  [59] = {.lex_state = 4, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 5},
  [61] = {.lex_state = 1, .external_lex_state = 2},
  [62] = {.lex_state = 4, .external_lex_state = 4},
  [63] = {.lex_state = 4, .external_lex_state = 2},
  [64] = {.lex_state = 4, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 4, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 6},
  [71] = {.lex_state = 4, .external_lex_state = 4},
  [72] = {.lex_state = 4, .external_lex_state = 4},
  [73] = {.lex_state = 4, .external_lex_state = 4},
  [74] = {.lex_state = 2, .external_lex_state = 2},
  [75] = {.lex_state = 2, .external_lex_state = 2},
  [76] = {.lex_state = 3, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 6},
  [78] = {.lex_state = 0, .external_lex_state = 6},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 6},
  [81] = {.lex_state = 0, .external_lex_state = 6},
  [82] = {.lex_state = 3, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 7},
  [84] = {.lex_state = 0, .external_lex_state = 8},
  [85] = {.lex_state = 4, .external_lex_state = 2},
  [86] = {.lex_state = 4, .external_lex_state = 2},
  [87] = {.lex_state = 4, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 9},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 12, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 9},
  [112] = {.lex_state = 12, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_start_tag_name = 0,
  ts_external_token_script_start_tag_name = 1,
  ts_external_token_style_start_tag_name = 2,
  ts_external_token_end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token_implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_start_tag_name] = sym_start_tag_name,
  [ts_external_token_script_start_tag_name] = sym_script_start_tag_name,
  [ts_external_token_style_start_tag_name] = sym_style_start_tag_name,
  [ts_external_token_end_tag_name] = sym_end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_implicit_end_tag] = sym_implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_semgrep_metavariable] = ACTIONS(1),
    [sym_start_tag_name] = ACTIONS(1),
    [sym_script_start_tag_name] = ACTIONS(1),
    [sym_style_start_tag_name] = ACTIONS(1),
    [sym_end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym_implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(102),
    [sym_doctype_] = STATE(27),
    [sym_node] = STATE(12),
    [sym_element] = STATE(27),
    [sym_script_element] = STATE(27),
    [sym_style_element] = STATE(27),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(70),
    [sym_style_start_tag] = STATE(68),
    [sym_self_closing_tag] = STATE(15),
    [sym_erroneous_end_tag] = STATE(27),
    [sym_semgrep_element] = STATE(15),
    [sym_semgrep_start_tag] = STATE(11),
    [aux_sym_fragment_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(23), 1,
      sym_implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_semgrep_start_tag,
    STATE(40), 1,
      sym_end_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(9), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(18), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(19), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [49] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(25), 1,
      sym_implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_semgrep_start_tag,
    STATE(16), 1,
      sym_end_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(2), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(18), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(19), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [98] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_semgrep_start_tag,
    STATE(22), 1,
      sym_end_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(5), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(18), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(19), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [147] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      sym_implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_semgrep_start_tag,
    STATE(44), 1,
      sym_end_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(9), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(18), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(19), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [196] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_LT_BANG,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      anon_sym_LT_SLASH,
    ACTIONS(44), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(6), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [242] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(38), 1,
      sym_semgrep_end_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(6), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [288] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(24), 1,
      sym_semgrep_end_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [334] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      sym_implicit_end_tag,
    ACTIONS(49), 1,
      anon_sym_LT_BANG,
    ACTIONS(52), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(58), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 1,
      sym_semgrep_start_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(9), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(18), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(19), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [380] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(48), 1,
      sym_semgrep_end_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(6), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [426] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(30), 1,
      sym_semgrep_end_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(10), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [472] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_semgrep_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(6), 2,
      sym_node,
      aux_sym_fragment_repeat1,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_semgrep_element,
    STATE(27), 5,
      sym_doctype_,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
  [518] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(65), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [531] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      sym_attribute_name,
    ACTIONS(69), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [546] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(76), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(78), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [572] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_GT,
    ACTIONS(84), 1,
      anon_sym_SLASH_GT,
    ACTIONS(86), 1,
      sym_attribute_name,
    STATE(20), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [589] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(76), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(88), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [615] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_attribute_name,
    ACTIONS(92), 1,
      anon_sym_GT,
    ACTIONS(94), 1,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [632] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(96), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(78), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [658] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_attribute_name,
    ACTIONS(92), 1,
      anon_sym_GT,
    ACTIONS(100), 1,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(102), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [688] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_GT,
    ACTIONS(86), 1,
      sym_attribute_name,
    ACTIONS(106), 1,
      anon_sym_SLASH_GT,
    STATE(23), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [705] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(110), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(88), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(96), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [744] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(112), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [757] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(102), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [770] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(116), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(120), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(116), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(65), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [822] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(124), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(128), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(112), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [861] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(132), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(136), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [887] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(140), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [900] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(110), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(136), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(144), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(140), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [952] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(150), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [965] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(144), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [978] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(150), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(132), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1004] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(128), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1017] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(124), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1030] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      sym_implicit_end_tag,
      sym_text,
    ACTIONS(152), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1043] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_attribute_value,
    ACTIONS(158), 1,
      anon_sym_SQUOTE,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      sym_quoted_attribute_value,
  [1059] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_attribute_name,
    ACTIONS(162), 1,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1073] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_text,
    ACTIONS(164), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1085] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_GT,
    ACTIONS(170), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1099] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_text,
    ACTIONS(172), 3,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [1111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_attribute_name,
    ACTIONS(176), 1,
      anon_sym_GT,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1125] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(178), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_GT,
    ACTIONS(182), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1151] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_semgrep_metavariable,
    ACTIONS(187), 1,
      sym_start_tag_name,
    ACTIONS(189), 1,
      sym_script_start_tag_name,
    ACTIONS(191), 1,
      sym_style_start_tag_name,
  [1167] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_attribute_value,
    ACTIONS(195), 1,
      anon_sym_SQUOTE,
    ACTIONS(197), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_quoted_attribute_value,
  [1183] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_attribute_name,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_attribute_name,
    ACTIONS(201), 1,
      anon_sym_GT,
    STATE(55), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_attribute_name,
    ACTIONS(203), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1225] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_semgrep_metavariable,
    ACTIONS(189), 1,
      sym_script_start_tag_name,
    ACTIONS(191), 1,
      sym_style_start_tag_name,
    ACTIONS(205), 1,
      sym_start_tag_name,
  [1241] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    ACTIONS(209), 1,
      sym_raw_text,
    STATE(21), 1,
      sym_end_tag,
  [1254] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_EQ,
    ACTIONS(178), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_LT_SLASH,
    ACTIONS(215), 1,
      sym_raw_text,
    STATE(28), 1,
      sym_end_tag,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    ACTIONS(217), 1,
      sym_raw_text,
    STATE(41), 1,
      sym_end_tag,
  [1291] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_LT_SLASH,
    ACTIONS(219), 1,
      sym_raw_text,
    STATE(26), 1,
      sym_end_tag,
  [1304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1331] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      sym_pat_98d585a,
  [1341] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    ACTIONS(233), 1,
      sym_pat_98d585a,
  [1351] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    ACTIONS(235), 1,
      sym_pat_58fbb2e,
  [1361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    STATE(47), 1,
      sym_end_tag,
  [1387] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_SQUOTE,
    ACTIONS(245), 1,
      sym_pat_58fbb2e,
  [1413] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_end_tag_name,
    ACTIONS(249), 1,
      sym_erroneous_end_tag_name,
  [1423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_semgrep_metavariable,
    ACTIONS(253), 1,
      sym_erroneous_end_tag_name,
  [1433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    STATE(43), 1,
      sym_end_tag,
  [1467] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(255), 1,
      sym_end_tag_name,
  [1477] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_LT_SLASH,
    STATE(45), 1,
      sym_end_tag,
  [1487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(257), 1,
      sym_semgrep_metavariable,
  [1497] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_end_tag,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_GT,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_erroneous_end_tag_name,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_GT,
  [1528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_doctype,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_end_tag_name,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_GT,
  [1549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_SQUOTE,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_GT,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_GT,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_GT,
  [1584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_SQUOTE,
  [1598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_DQUOTE,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_GT,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_erroneous_end_tag_name,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_pat_03aa317,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_GT,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_end_tag_name,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_pat_03aa317,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_doctype,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 147,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 242,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 334,
  [SMALL_STATE(10)] = 380,
  [SMALL_STATE(11)] = 426,
  [SMALL_STATE(12)] = 472,
  [SMALL_STATE(13)] = 518,
  [SMALL_STATE(14)] = 531,
  [SMALL_STATE(15)] = 546,
  [SMALL_STATE(16)] = 559,
  [SMALL_STATE(17)] = 572,
  [SMALL_STATE(18)] = 589,
  [SMALL_STATE(19)] = 602,
  [SMALL_STATE(20)] = 615,
  [SMALL_STATE(21)] = 632,
  [SMALL_STATE(22)] = 645,
  [SMALL_STATE(23)] = 658,
  [SMALL_STATE(24)] = 675,
  [SMALL_STATE(25)] = 688,
  [SMALL_STATE(26)] = 705,
  [SMALL_STATE(27)] = 718,
  [SMALL_STATE(28)] = 731,
  [SMALL_STATE(29)] = 744,
  [SMALL_STATE(30)] = 757,
  [SMALL_STATE(31)] = 770,
  [SMALL_STATE(32)] = 783,
  [SMALL_STATE(33)] = 796,
  [SMALL_STATE(34)] = 809,
  [SMALL_STATE(35)] = 822,
  [SMALL_STATE(36)] = 835,
  [SMALL_STATE(37)] = 848,
  [SMALL_STATE(38)] = 861,
  [SMALL_STATE(39)] = 874,
  [SMALL_STATE(40)] = 887,
  [SMALL_STATE(41)] = 900,
  [SMALL_STATE(42)] = 913,
  [SMALL_STATE(43)] = 926,
  [SMALL_STATE(44)] = 939,
  [SMALL_STATE(45)] = 952,
  [SMALL_STATE(46)] = 965,
  [SMALL_STATE(47)] = 978,
  [SMALL_STATE(48)] = 991,
  [SMALL_STATE(49)] = 1004,
  [SMALL_STATE(50)] = 1017,
  [SMALL_STATE(51)] = 1030,
  [SMALL_STATE(52)] = 1043,
  [SMALL_STATE(53)] = 1059,
  [SMALL_STATE(54)] = 1073,
  [SMALL_STATE(55)] = 1085,
  [SMALL_STATE(56)] = 1099,
  [SMALL_STATE(57)] = 1111,
  [SMALL_STATE(58)] = 1125,
  [SMALL_STATE(59)] = 1137,
  [SMALL_STATE(60)] = 1151,
  [SMALL_STATE(61)] = 1167,
  [SMALL_STATE(62)] = 1183,
  [SMALL_STATE(63)] = 1197,
  [SMALL_STATE(64)] = 1211,
  [SMALL_STATE(65)] = 1225,
  [SMALL_STATE(66)] = 1241,
  [SMALL_STATE(67)] = 1254,
  [SMALL_STATE(68)] = 1265,
  [SMALL_STATE(69)] = 1278,
  [SMALL_STATE(70)] = 1291,
  [SMALL_STATE(71)] = 1304,
  [SMALL_STATE(72)] = 1313,
  [SMALL_STATE(73)] = 1322,
  [SMALL_STATE(74)] = 1331,
  [SMALL_STATE(75)] = 1341,
  [SMALL_STATE(76)] = 1351,
  [SMALL_STATE(77)] = 1361,
  [SMALL_STATE(78)] = 1369,
  [SMALL_STATE(79)] = 1377,
  [SMALL_STATE(80)] = 1387,
  [SMALL_STATE(81)] = 1395,
  [SMALL_STATE(82)] = 1403,
  [SMALL_STATE(83)] = 1413,
  [SMALL_STATE(84)] = 1423,
  [SMALL_STATE(85)] = 1433,
  [SMALL_STATE(86)] = 1441,
  [SMALL_STATE(87)] = 1449,
  [SMALL_STATE(88)] = 1457,
  [SMALL_STATE(89)] = 1467,
  [SMALL_STATE(90)] = 1477,
  [SMALL_STATE(91)] = 1487,
  [SMALL_STATE(92)] = 1497,
  [SMALL_STATE(93)] = 1507,
  [SMALL_STATE(94)] = 1514,
  [SMALL_STATE(95)] = 1521,
  [SMALL_STATE(96)] = 1528,
  [SMALL_STATE(97)] = 1535,
  [SMALL_STATE(98)] = 1542,
  [SMALL_STATE(99)] = 1549,
  [SMALL_STATE(100)] = 1556,
  [SMALL_STATE(101)] = 1563,
  [SMALL_STATE(102)] = 1570,
  [SMALL_STATE(103)] = 1577,
  [SMALL_STATE(104)] = 1584,
  [SMALL_STATE(105)] = 1591,
  [SMALL_STATE(106)] = 1598,
  [SMALL_STATE(107)] = 1605,
  [SMALL_STATE(108)] = 1612,
  [SMALL_STATE(109)] = 1619,
  [SMALL_STATE(110)] = 1626,
  [SMALL_STATE(111)] = 1633,
  [SMALL_STATE(112)] = 1640,
  [SMALL_STATE(113)] = 1647,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(96),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(60),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(94),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(27),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(113),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(65),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(108),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(19),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_end_tag, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_end_tag, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(58),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_element, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_element, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype_, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype_, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_element, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_element, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_start_tag, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_start_tag, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_semgrep_start_tag, 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semgrep_start_tag, 4),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(67),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [273] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = (const uint16_t *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
